Error 2021-02-03 08:40:27: Exception while attempting zmq : [Error: /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
	at process.func [as dlopen] (electron/js2c/asar.js:140:31)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1081:18)
	at Object.func [as .node] (electron/js2c/asar.js:140:31)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1092:657)
	at Function.i._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1061:334)
	at Function.n._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:567)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/snap/code/52/usr/share/code/resources/app/out/vs/loader.js:16:346)
	at load (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/node-gyp-build/index.js:21:10)
	at Object.<anonymous> (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/lib/native.js:6:43)
	at Module.o._compile (/snap/code/52/usr/share/code/resources/app/out/vs/loader.js:16:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1092:657)
	at Function.i._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1061:334)
	at Function.n._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:567)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/snap/code/52/usr/share/code/resources/app/out/vs/loader.js:16:346)
	at Object.<anonymous> (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/lib/index.js:3:16)
	at Module.o._compile (/snap/code/52/usr/share/code/resources/app/out/vs/loader.js:16:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1092:657)
	at Function.i._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1061:334)
	at Function.n._load (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:567)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/snap/code/52/usr/share/code/resources/app/out/vs/loader.js:16:346)
	at Object.<anonymous> (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:274679)
	at n (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:186)
	at /home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:803883
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async u.zmqSupportedImpl (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:803850)]
Error 2021-02-03 08:40:27: Jupyter Extension (Error in Failed to update settings.json, method:fixSettingsFile): [EntryNotFound (FileSystemError): Unable to read file '/home/kyleaubuchon/.config/Code/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/kyleaubuchon/.config/Code/User/settings.json')
	at _handleError (/snap/code/52/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:745:473)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async m.readFile (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:832552)
	at async g.fixSettingsFile (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:288845)
	at async Promise.all (index 0)
	at async g.updateSettings (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:290565)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
Error 2021-02-03 08:40:34: DataScience Error [SyntaxError: Unexpected token c in JSON at position 0
	at JSON.parse (<anonymous>)
	at r.loadContents (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:181157)
	at r.loadFromFile (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:180741)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async T.loadModel (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:613437)
	at async T.createNew (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:613162)
	at async p.openNotebook (/home/kyleaubuchon/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:398188)
	at async E.onMessage (/home/kyleaubuchon/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:893535)]
